<?php
/** @var Afterpay\Afterpay\Block\Cta\MiniCartHeadless $block */
/** @var Afterpay\Afterpay\ViewModel\Container\Cta\Headless $viewModel */
$viewModel = $block->getViewModel();
$utilityJsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/service/utils/wait-for-selector.js');
$jsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/view/container/cta/minicart/headless.js');
?>
<script>
    if (typeof afterpayCurrency === 'undefined') {
        window.afterpayCurrency = "<?= /* @noEscape */ $viewModel->getCurrency() ?>";
    }
</script>
<script src="<?= /** @noEscape */ $utilityJsUrl ?>"></script>
<script src="<?= /** @noEscape */ $jsUrl ?>" async></script>
