<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Afterpay\Afterpay\ViewModel\Container\ExpressCheckout\ExpressCheckout $viewModel */

use Afterpay\Afterpay\ViewModel\Container\ExpressCheckout\ExpressCheckoutPdp;

$viewModel = $block->getViewModel();
$enabled = $viewModel->isContainerEnable();
if ($enabled && $viewModel instanceof ExpressCheckoutPdp && $viewModel->isRestrictedProductInCart()) {
    $enabled = false;
}
?>
<?php if ($enabled): ?>
<div class="afterpay-container-express-checkout" data-bind="scope: 'afterpay.express.checkout'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= /** @noEscape */ $viewModel->updateJsLayout($block->getJsLayout()) ?>
        }
    }
</script>
<?php endif; ?>
