<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Afterpay\Afterpay\ViewModel\Container\ExpressCheckout\Headless $viewModel */

$viewModel = $block->getViewModel();
$utilityJsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/service/utils/wait-for-selector.js');
$jsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/view/container/express-checkout/cart/headless.js');
$externalJsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/view/container/express-checkout/cart/express-checkout-cart-widget.js');

$loadingHtml = '';
// Check if Hyva theme is active
$isHyva = $viewModel->isHyva();
if ($isHyva) {
    $loadingHtml = $block->getChildHtml('loading');
    if (!$loadingHtml) {
        $loadingHtml = $block->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('Afterpay_Afterpay::hyva/ui/loading.phtml')
            ->toHtml();
    }
}
?>

<script>
    if (typeof afterpayCartId === 'undefined') {
        var afterpayCartId = "<?= /* @noEscape */ $viewModel->getCartId() ?>";
    }
    if (typeof afterpayStoreId === 'undefined') {
        var afterpayStoreId = "<?= /* @noEscape */ $viewModel->getStoreId() ?>";
    }
    if (typeof afterpayLocaleCode === 'undefined') {
        var afterpayLocaleCode = "<?= /* @noEscape */ $viewModel->getCountryCode() ?>";
    }
</script>

<script src="<?= $escaper->escapeUrl($utilityJsUrl) ?>"></script>
<script src="<?= $escaper->escapeUrl($jsUrl) ?>" async></script>
<script src="<?= $escaper->escapeUrl($externalJsUrl) ?>" async></script>
<?php if ($isHyva): ?>
<script>
    'use strict';

    function initHyvaCartLoaderComponent() {
        return {
            isLoading: false,
            startLoaderCart() {
                this.isLoading = true;
            },
            stopLoaderCart() {
                this.isLoading = false;
            }
        }
    }
</script>
<?php endif; ?>

<section <?= $isHyva ? 'x-data="initHyvaCartLoaderComponent()" @start-loader-cart.window="startLoaderCart()" @processStop.window="stopLoaderCart()"' : '' ?>
         id="headless-afterpay-cart-ec" class="headless-afterpay-ec hidden headless-afterpay-cart-ec">
    <?php if ($isHyva): ?>
    <div x-show="isLoading">
        <?= /* @noEscape */ $loadingHtml ?>
    </div>
    <?php endif; ?>
    <div class="afterpay-express-checkout-product-wrapper">
        <button class="afterpay-express-button afterpay-express-button-cart">
            <img src="<?= $escaper->escapeUrl($viewModel->getImageurl()) ?>"
                 alt="<?= /* @noEscape */ __('Checkout with Afterpay') ?>"/>
        </button>
        <div class="hidden" id="afterpay-button-cart" data-afterpay-entry-point="cart"></div>
    </div>
</section>
