<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Afterpay\Afterpay\ViewModel\Container\ExpressCheckout\Headless $viewModel */
$viewModel = $block->getViewModel();
$utilityJsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/service/utils/wait-for-selector.js');
$jsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/view/container/express-checkout/product/headless.js');
$externalJsUrl = $block->getViewFileUrl('Afterpay_Afterpay::js/view/container/express-checkout/product/express-checkout-widget.js');

$loadingHtml = '';
// Check if Hyva theme is active
$isHyva = $viewModel->isHyva();
if ($isHyva) {
    $loadingHtml = $block->getChildHtml('loading');
    if (!$loadingHtml) {
        $loadingHtml = $block->getLayout()
            ->createBlock(\Magento\Framework\View\Element\Template::class)
            ->setTemplate('Afterpay_Afterpay::hyva/ui/loading.phtml')
            ->toHtml();
    }
}
?>
<?php if (!$viewModel->isRestrictedProductInCart()) : ?>
<script>
    if (typeof afterpayLocaleCode === 'undefined') {
        var afterpayLocaleCode = "<?= /* @noEscape */ (string)$viewModel->getCountryCode() ?>";
    }
    if (typeof afterpayProductSku === 'undefined') {
        var afterpayProductSku = "<?= /* @noEscape */ $viewModel->getProductSku() ?>";
    }
    if (typeof afterpayStoreId === 'undefined') {
        var afterpayStoreId = "<?= /* @noEscape */ $viewModel->getStoreId() ?>";
    }
</script>
<script src="<?= $escaper->escapeUrl($utilityJsUrl) ?>"></script>
<script src="<?= $escaper->escapeUrl($jsUrl) ?>" async></script>
<script src="<?= $escaper->escapeUrl($externalJsUrl) ?>" async></script>
<?php if ($isHyva): ?>
<script>
    'use strict';

    function initHyvaLoaderComponent() {
        return {
            isLoading: false,
            startLoader() {
                this.isLoading = true;
            },
            stopLoader() {
                this.isLoading = false;
            }
        }
    }
</script>
<?php endif; ?>

<section <?= $isHyva ? 'x-data="initHyvaLoaderComponent()" @start-loader.window="startLoader()" @processStop.window="stopLoader()"' : '' ?> id="headless-afterpay-pdp-ec" class="headless-afterpay-ec hidden headless-afterpay-pdp-ec">
    <?php if ($isHyva): ?>
    <div x-show="isLoading">
        <?= /* @noEscape */ $loadingHtml ?>
    </div>
    <?php endif; ?>
    <div class="afterpay-express-checkout-product-wrapper">
        <button class="afterpay-express-button afterpay-express-pdp-button">
            <img src="<?= $escaper->escapeUrl($viewModel->getImageurl()) ?>"
                 alt="<?= /* @noEscape */ __('Checkout with Afterpay') ?>"/>
        </button>
        <div class="hidden" id="afterpay-button-pdp" data-afterpay-entry-point="product-page"></div>
    </div>
</section>
<?php endif; ?>
