<?php
/**
 * Magento 2 extensions for Afterpay Payment
 *
 * @author Afterpay
 * @copyright 2016-2020 Afterpay https://www.afterpay.com
 */
?>
<?php if ($block->canShow()) : ?>
	    <div class='payment-method-note afterpay-checkout-note' style='text-align: left; margin-bottom: 1.5rem; font-size: 13px;'><h3 style="font-size: 1.5rem"><span style="color: #00a4e4;">
	    <?php $assets_cart_page = $block->getCartPageText(); 
		echo $assets_cart_page['snippet1'];
		?>
		<span class="afterpay_instalment_price"> <?php echo $block->getInstallmentsTotalHtml();?></span>
		<?php
		echo $assets_cart_page['snippet2'];
		?>
	    </div>

	    <!--    Button buy now-->
	    <button type="button" data-role="proceed-to-checkout" onclick="window.location.href='<?php echo $block->getUrl('checkout', ['_secure' => true]);?>'" title="<?php echo __('Buy now, pay later') ?>" class="action primary btn-afterpay-checkout">
	        <img src="https://static.afterpay.com/integration/logo-afterpay-white-149x31.png" alt="<?php echo __('Buy now, pay later'); ?>" srcset="https://static.afterpay.com/integration/logo-afterpay-white-149x31.png 1x,https://static.afterpay.com/integration/logo-afterpay-white-149x31@2x.png 2x,https://static.afterpay.com/integration/logo-afterpay-white-149x31@3px.png 3x" height="31"/>
	    </button>
<?php endif; ?>
