<?php
/**
 * Magento 2 extensions for Afterpay Payment
 *
 * @author Afterpay
 * @copyright 2016-2020 Afterpay https://www.afterpay.com
 */
$enable_cbt = $this->helper('Afterpay\Afterpay\Helper\Data')->getConfig('payment/afterpaypayovertime/enable_cbt');
$store_base_currency = $this->helper('Afterpay\Afterpay\Helper\Data')->getConfig('currency/options/default');
if(!$enable_cbt){
	$enable_cbt = 0;
}
?>
<div id="afterpay-modal-popup" style="display:none">
    <a href="https://www.afterpay.com/terms/" target="_blank">
        <img class="afterpay-modal-image" alt="Afterpay"/>
    </a>
</div>
<script>
	require(
        [
            'jquery',
			'Magento_Ui/js/modal/modal'
		],
        function(
            $,
			modal
        ){
			var storeCurrency="<?php echo $store_base_currency;?>";
			var enable_cbt=<?php echo $enable_cbt;?>;
			var width=$(window).width();
			
			if(storeCurrency=="USD" && !$("#afterpay-modal-container").length){
			$('head').append('<link rel="stylesheet" href="https://static.afterpay.com/modal/us.css" type="text/css" src_type="url"/>');
			 $.ajax({
				url: 'https://static.afterpay.com/modal/us.html',
				complete: function(jqXHR, textStatus) {
				  if (jqXHR.status == 200) {
					$('#maincontent')
					  .append(jqXHR.responseText);
					}
				}
			 });	
			}
			
			var options = {
                responsive: false,
                innerScroll: false,
                modalClass: 'afterpay-learn-more'
            };
            // register poup
            var popup = modal(options, $('#afterpay-modal-popup'));
			
			if(enable_cbt){
				if(width > 640){
					$("#afterpay-modal-popup .afterpay-modal-image").attr({src:"https://static.afterpay.com/lightbox-desktop-cbt.png",srcset:"https://static.afterpay.com/lightbox-desktop-cbt.png 1x,https://static.afterpay.com/lightbox-desktop-cbt@2x.png 2x,https://static.afterpay.com/lightbox-desktop-cbt@3x.png 3x"});
				}
				else{
					$("#afterpay-modal-popup .afterpay-modal-image").attr({src:"https://static.afterpay.com/lightbox-mobile.png",srcset:"https://static.afterpay.com/lightbox-mobile-cbt.png 1x,https://static.afterpay.com/lightbox-mobile-cbt@2x.png 2x,https://static.afterpay.com/lightbox-mobile-cbt@3x.png 3x"});
				}
			}
			else{
				if(width > 640){
					$("#afterpay-modal-popup .afterpay-modal-image").attr({src:"https://static.afterpay.com/lightbox-desktop.png",srcset:"https://static.afterpay.com/lightbox-desktop.png 1x,https://static.afterpay.com/lightbox-desktop@2x.png 2x,https://static.afterpay.com/lightbox-desktop@3x.png 3x"});
				}
				else{
					$("#afterpay-modal-popup .afterpay-modal-image").attr({src:"https://static.afterpay.com/lightbox-mobile.png",srcset:"https://static.afterpay.com/lightbox-mobile.png 1x,https://static.afterpay.com/lightbox-mobile@2x.png 2x,https://static.afterpay.com/lightbox-mobile@3x.png 3x"});
				}
			}

            // register the click to be popup
            $( ".afterpay-modal-popup-trigger" ).on( "click", function() {
                $('#afterpay-modal-popup').show();
                $('#afterpay-modal-popup').modal('openModal');
            });

            // register the click to be popup
            $( ".afterpay-modal-popup-trigger-us" ).on( "click", function() {
                if($("#afterpay-modal-container").length!=0){
					var popup_us = modal(options, $('#afterpay-modal-content'));
					$('#afterpay-modal-content').show();
					$('#afterpay-modal-content').modal('openModal');
				}
            });
		}
	);
</script>

