<?php
/**
 * Magento 2 extensions for Afterpay Payment
 *
 * @author Afterpay
 * @copyright 2016-2021 Afterpay https://www.afterpay.com
 */
/** @var Afterpay\Afterpay\Block\Catalog\Installments $block */

$product_type = $block->getTypeOfProduct();
$data_amount = $block->getFinalAmount();

if ($block->isPaymentMethodActive() && $product_type != "grouped" && $block->canUseCurrency() && $data_amount > 0) {
    $afterpay_eligible = "true";
    if (($block->canShow() === false)) {
        $afterpay_eligible = "false";
    }
    $min_limit = $block->getMinOrderLimit();
    $show_lower_limit = "true";
    if ((float)$min_limit < 1) {
        $show_lower_limit = "false";
    }
    $max_limit = $block->getMaxOrderLimit();
    $productPriceFormat = $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore());
    $priceFormat = $block->getJsonDecode($productPriceFormat);
    $isECenabled=$block->isDisplayEConProductPage();
    $isDisplay=(int)$block->isDisplayOnProductPage();
    if (!$block->isDisplayECOnMiniCart()) {
        ?>
        <script src="<?= $block->escapeUrl($block->getAfterpayECJsUrl()); ?>" async></script>
    <?php }
    if ($block->isDisplayOnProductPage()) { ?>
        <script
            src="<?= $block->escapeUrl($block->getAfterpayJsLibUrl()); ?>"
            data-min="<?= /* @noEscape */ $min_limit; ?>"
            data-max="<?= /* @noEscape */ $max_limit; ?>" async></script>
        <?php
        $store_currency = $block->getCurrentCurrency();
        $data_locale = $block->getCurrentLocale();

        $enable_cbt = $this->helper('Afterpay\Afterpay\Helper\Data')->getConfig('payment/afterpaypayovertime/enable_cbt');
        $data_enable_cbt = !empty($enable_cbt) ? "true" : "false";
        ?>
        <afterpay-placement
            data-locale="<?= /* @noEscape */ $data_locale; ?>"
            data-currency="<?= /* @noEscape */ $store_currency; ?>"
            data-amount="<?= /* @noEscape */ $data_amount; ?>"
            data-is-eligible="<?= /* @noEscape */ $afterpay_eligible; ?>"
            data-cbt-enabled="<?= /* @noEscape */ $data_enable_cbt; ?>"
            data-show-lower-limit="<?= /* @noEscape */ $show_lower_limit; ?>"
            data-decimal-separator="<?= /* @noEscape */ $priceFormat["decimalSymbol"]; ?>"
            data-thousands-separator="<?= /* @noEscape */ $priceFormat["groupSymbol"]; ?>"></afterpay-placement>

        <?php
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Afterpay_Afterpay/js/view/product/afterpay-products": {
                    "afterpayConfig":<?php echo $block->getAfterpayConfigs(); ?>,
                    "productPriceFormat":<?php echo $productPriceFormat; ?>,
                    "isECenabled":<?php echo $isECenabled;?>,
                    "isDisplay":<?php echo $isDisplay;?>
                }
            }
        }
    </script>
   <?php if ($block->isDisplayEConProductPage() && $afterpay_eligible != "false") { ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Afterpay_Afterpay/js/view/express/afterpay-express": {
                    "afterpayConfig":<?php echo $block->getAfterpayConfigs(); ?>,
                    "isProductVirtual":"<?php echo $block->isProductVirtual(); ?>",
                    "productType":"<?php echo $product_type; ?>"
                }
            }
        }
        </script>
        <button id="afterpay-pdp-express-button" data-afterpay-entry-point="product-page" class="afterpay primary express-button" style="display: none;">
            <img id="afterpay-express-start"
                 src="https://static.afterpay.com/button/checkout-with-afterpay/white-on-black.svg"
                 alt="Checkout with Afterpay"/>
        </button>
    <?php }
} ?>

