<?php
/**
 * Magento 2 extensions for Afterpay Payment
 *
 * @author Afterpay
 * @copyright 2016-2018 Afterpay https://www.afterpay.com
 */
?>
<?php 
//Check for supported currency (AUD,NZD and USD)
$canUseCurrency = $block->canUseCurrency();

//If currency is supported, check if Afterpay is enabled.
if($canUseCurrency) {
	if (!$block->canShow()) {
		$hide = "display:none;";
		$showAfterpay = false;
	} else {
		$hide = "";
		$showAfterpay = true;
	}
}

if($canUseCurrency) : ?>
	<div showAfterpay="<?php echo $showAfterpay; ?>" maxLimit="<?php echo $block->getMaxOrderLimit(); ?>" minLimit="<?php echo $block->getMinOrderLimit(); ?>" style="position: relative; font-style: italic; line-height: 1.4; <?php echo $hide; ?>" class="afterpay-installments afterpay-installments-amount">
	<?php $assets_product_page = $block->getInstalmentText(); 
	echo $assets_product_page['snippet1'];
	?>
	<span class="afterpay_instalment_price"><?php echo $block->getInstallmentsAmount(); ?></span>
		<br/>
	<?php
	$assets_product_snippet2  = $assets_product_page['snippet2'];
	$assets_product_snippet2 = str_replace(array('[modal-href]'), 
	                    array('javascript:void(0)'), $assets_product_snippet2);
	echo $assets_product_snippet2;
	?>
	</div>
<?php endif; ?>
