<?php
/**
 * Magento 2 extensions for Afterpay Payment
 *
 * @author Afterpay
 * @copyright 2016-2019 Afterpay https://www.afterpay.com
 */
?>
<div id="afterpay-modal-popup" style="display:none">
    <a href="https://www.afterpay.com/terms/" target="_blank">
        <img class="afterpay-modal-image" src="https://static.secure-afterpay.com.au/banner-large.png" alt="Afterpay"/>
        <img class="afterpay-modal-image-mobile" src="https://static.secure-afterpay.com.au/modal-mobile.png" alt="Afterpay"/>
    </a>
</div>
<div id="afterpay-modal-popup-us" style="display:none">
    <a href="https://www.afterpay.com/purchase-payment-agreement" target="_blank">
        <img class="afterpay-modal-image" src="https://static.afterpay.com/us-popup-medium.png" alt="Afterpay"/>
        <img class="afterpay-modal-image-mobile" src="https://static.afterpay.com/us-popup-small.png" alt="Afterpay"/>
    </a>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                responsive: false,
                innerScroll: false,
                modalClass: 'afterpay-learn-more'
            };
            // register poup
            var popup = modal(options, $('#afterpay-modal-popup'));
            var popup_us = modal(options, $('#afterpay-modal-popup-us'));

            // register the click to be popup
            $( ".afterpay-modal-popup-trigger" ).on( "click", function() {
                $('#afterpay-modal-popup').show();
                $('#afterpay-modal-popup').modal('openModal');
            });

            // register the click to be popup
            $( ".afterpay-modal-popup-trigger-us" ).on( "click", function() {
                $('#afterpay-modal-popup-us').show();
                $('#afterpay-modal-popup-us').modal('openModal');
            });
        }
    );
</script>

